config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :walks do
    get 'all', on: :collection
    resources :pets, only: [:show]
  end

  resources :owners do
    resources :pets
  end

  resources :users
  resources :pets

  get '/auth/google_oauth2/callback', to: 'static#google_login'

  root 'static#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :user, optional: true
  has_many :pets, dependent: :nullify
  has_many :walks, through: :pets
  has_one_attached :entry_instructions_photo

  validates :fname, presence: true
  # validates :lname, presence: true
  validates :phone, presence: true

  accepts_nested_attributes_for :pets

  before_save :update_neighborhood

  def name
    "#{fname} #{lname}"
  end

  private

  def update_neighborhood
    if neighborhood.blank? && will_save_change_to_zip_code?
      self.neighborhood = NycNeighborhoods.neighborhood(zip_code)
    end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_owner, only: [:show, :edit, :update]
  include ActionView::Helpers::NumberHelper

  def index
    @owners = Owner.all.order(:fname)
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.create owner_params
    redirect_to owner_path(@owner)
  end

  def show
    redirect_to owner_pets_path(@owner)
  end

  def edit
  end

  def update
    if @owner.update owner_params
      redirect_to owner_path(@owner)
    else
      flash.alert = @owner.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_owner
    @owner = Owner.find params[:id]
  end

  def owner_params
    params[:owner][:phone] = number_to_phone(params[:owner][:phone], pattern: /(\d{1,4})(\d{3})(\d{4})$/, area_code: true)
    params[:owner][:phone2] = number_to_phone(params[:owner][:phone2], pattern: /(\d{1,4})(\d{3})(\d{4})$/, area_code: true)
    params.require(:owner).permit(
      :fname,
      :lname,
      :phone,
      :email,
      :role,
      :password,
      :password_confirmation,
      :address,
      :apartment_number,
      :zip_code,
      :door_code,
      :lockbox_code,
      :entry_instructions,
      :neighborhood,
      :phone2,
      :entry_instructions_photo
    )
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for @owner, html: { class: "w3-container" } do |f| %>
  <% if @owner.errors.any? %>
    <div class="w3-panel w3-red w3-padding w3-margin-bottom w3-round">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-red w3-large w3-display-topright w3-round">&times;</span>
      <h3><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h3>
      <ul class="w3-ul">
        <% @owner.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :fname, 'First Name', class: "w3-text-grey" %>
    <%= f.text_field :fname, class: "w3-input w3-border w3-round", required: true %>
  </p>

  <p>
    <%= f.label :lname, 'Last Name', class: "w3-text-grey" %>
    <%= f.text_field :lname, class: "w3-input w3-border w3-round", required: true %>
  </p>

  <p>
    <%= f.label :email, 'Email', class: "w3-text-grey" %>
    <%= f.email_field :email, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :phone, 'Primary Phone #', class: "w3-text-grey" %>
    <%= f.telephone_field :phone, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :phone2, 'Secondary Phone #', class: "w3-text-grey" %>
    <%= f.telephone_field :phone2, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :neighborhood, 'Neighborhood', class: "w3-text-grey" %>
    <%= f.text_field :neighborhood, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :address, 'Street Address', class: "w3-text-grey" %>
    <%= f.text_field :address, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :apartment_number, 'Apartment #', class: "w3-text-grey" %>
    <%= f.text_field :apartment_number, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :zip_code, 'Zip Code', class: "w3-text-grey" %>
    <%= f.text_field :zip_code, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :door_code, 'Door Code', class: "w3-text-grey" %>
    <%= f.text_field :door_code, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :lockbox_code, 'Lockbox Code', class: "w3-text-grey" %>
    <%= f.text_field :lockbox_code, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :entry_instructions, 'Entry Instructions', class: "w3-text-grey" %>
    <%= f.text_area :entry_instructions, class: "w3-input w3-border w3-round", rows: 4 %>
  </p>

  <p>
    <%= f.label :entry_instructions_photo, "Lockbox / Entry Photo", class: "w3-text-grey" %>
    <%= f.file_field :entry_instructions_photo, class: "w3-input w3-border w3-round" %>
  </p>

  <p class="w3-center w3-padding-16">
    <%= f.submit (@owner.new_record? ? "Create Owner" : "Update Owner"), class: "w3-button w3-black w3-round-large w3-hover-dark-grey w3-padding-large" %>
  </p>
<% end %>

app/views/owners/_owner.html.erb
<li class="w3-bar w3-padding">
  <div class="w3-bar-item">
    <span class="w3-large"><%= link_to owner.name, owner_path(owner) %></span><br>
    <span>Neighborhood: <%= owner.neighborhood %></span><br>
    <span>Primary Phone: <%= owner.phone %></span>
  </div>
</li> 

app/views/owners/_show.html.erb
<%
  address_value = nil
  if @owner.address.present?
    add = @owner.address
    add += "<br>#{@owner.zip_code}" if @owner.zip_code.present?
    add += "<br>" + link_to('View on Google Maps', "https://www.google.com/maps/place/#{@owner.address.gsub(' ', '+')},+#{@owner.zip_code}", target: '_blank', class: 'w3-text-blue w3-hover-text-light-blue')
    address_value = add.html_safe
  end

  entry_instructions_value = @owner.entry_instructions
  if @owner.entry_instructions_photo.attached?
    entry_instructions_value += "<br>" + image_tag(@owner.entry_instructions_photo, class: "w3-margin-top", style: "width:100%; height:auto; object-fit: cover;")
    entry_instructions_value = entry_instructions_value.html_safe
  end

  attributes = [
    { label: "Email", value: @owner.email },
    { label: "Primary Phone", value: (@owner.phone.present? ? link_to(@owner.phone, "tel:#{@owner.phone}") : nil) },
    { label: "Secondary Phone", value: (@owner.phone2.present? ? link_to(@owner.phone2, "tel:#{@owner.phone2}") : nil) },
    { label: "Address", value: address_value },
    { label: "Apartment #", value: @owner.apartment_number },
    { label: "Door Code", value: @owner.door_code },
    { label: "Lockbox Code", value: @owner.lockbox_code },
    { label: "Entry Instructions", value: entry_instructions_value },
    { label: "Profile Created", value: @owner.created_at.present? ? @owner.created_at.strftime("%B %d, %Y") : nil }
  ]

  # Determine the edit path based on the show_edit_button variable
  owner_edit_path = (defined?(show_edit_button) && show_edit_button) ? edit_owner_path(@owner) : nil
%>

<%= render 'layouts/show_page',
           title: @owner.name,
           subtitle: @owner.neighborhood,
           attributes: attributes,
           edit_path: owner_edit_path, # Use the conditional edit path
           resource_name: :owner,
           show_blank_values: false %>

app/views/owners/edit.html.erb
<%= render layout: 'shared/w3_content_card', locals: { title: "Edit Owner: #{@owner.name}", max_width: "700px" } do %>
  <%# Flash messages can be added here if needed, or handled by a global flash messages partial %>
  <%= render 'form', owner: @owner %>
<% end %>

app/views/owners/index.html.erb
<%= render 'layouts/index_page', title: 'Owners', new_path: new_owner_path, collection: @owners, resource_name: 'owner', new_text: "New Owner", item_partial: 'owners/owner' %>

app/views/owners/new.html.erb
<%= render layout: 'shared/w3_content_card', locals: { title: "Create New Owner", max_width: "700px" } do %>
  <%= render 'form', owner: @owner %>
<% end %>

app/views/owners/show.html.erb
<%
  address_value = nil
  if @owner.address.present?
    add = @owner.address
    add += "<br>#{@owner.zip_code}" if @owner.zip_code.present?
    add += "<br>" + link_to('View on Google Maps', "https://www.google.com/maps/place/#{@owner.address.gsub(' ', '+')},+#{@owner.zip_code}", target: '_blank', class: 'w3-text-blue w3-hover-text-light-blue')
    address_value = add.html_safe
  end

  entry_instructions_value = @owner.entry_instructions
  if @owner.entry_instructions_photo.attached?
    entry_instructions_value += "<br>" + image_tag(@owner.entry_instructions_photo, class: "w3-margin-top", style: "width:100%; height:auto; object-fit: cover;")
    entry_instructions_value = entry_instructions_value.html_safe
  end

  attributes = [
    { label: "Email", value: @owner.email },
    { label: "Primary Phone", value: (@owner.phone.present? ? link_to(@owner.phone, "tel:#{@owner.phone}") : nil) },
    { label: "Secondary Phone", value: (@owner.phone2.present? ? link_to(@owner.phone2, "tel:#{@owner.phone2}") : nil) },
    { label: "Address", value: address_value },
    { label: "Apartment #", value: @owner.apartment_number },
    { label: "Door Code", value: @owner.door_code },
    { label: "Lockbox Code", value: @owner.lockbox_code },
    { label: "Entry Instructions", value: entry_instructions_value },
    { label: "Profile Created", value: @owner.created_at.present? ? @owner.created_at.strftime("%B %d, %Y") : nil }
  ]
%>

<%= render 'layouts/show_page',
           title: @owner.name,
           subtitle: @owner.neighborhood,
           attributes: attributes,
           edit_path: edit_owner_path(@owner),
           resource_name: :owner,
           show_blank_values: false %> 