config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :walks do
    get 'all', on: :collection
    resources :pets, only: [:show]
  end

  resources :owners do
    resources :pets
  end

  resources :users
  resources :pets

  get '/auth/google_oauth2/callback', to: 'static#google_login'

  root 'static#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner, required: false
  has_many :walks
  has_many :users, through: :walks
  has_one_attached :image

  validates :name, presence: true

  scope :all_az, -> {all.order(:name)}

  PET_TYPES = ["Dog", "Cat"].freeze

  def name_with_owner
    if owner
      "#{name} (#{owner.name})"
    else
      "#{name} (no owner assigned)"
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pet, only: [:show, :edit, :update]

  def index
    if params[:owner_id]
      @owner = Owner.find(params[:owner_id])
      @pets = @owner.pets
    elsif params[:query]
      @pets = Pet.where("LOWER(name) ~ ?", "#{params[:query].downcase}")
    else
      @pets = Pet.all_az
    end
  end

  def new
    @pet = Pet.new
    if params[:owner_id]
      @pet.owner = Owner.find params[:owner_id]
    end
  end

  def create
    @pet = Pet.create(processed_pet_params)
    if @pet.persisted?
      redirect_to pet_path(@pet)
    else
      flash.alert = @pet.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @owner = @pet.owner
  end

  def edit
  end

  def update
    if @pet.update(processed_pet_params)
      redirect_to pet_path(@pet)
    else
      flash.alert = @pet.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_pet
    @pet = Pet.find params[:id]
  end

  def processed_pet_params
    current_params = pet_params
    if current_params[:pet_type] == 'Other'
      current_params[:pet_type] = params[:pet_type_other].presence
    end
    current_params
  end

  def pet_params
    params.require(:pet).permit(
      :name,
      :owner_id,
      :pet_type,
      :gender,
      :breed,
      :birthday,
      :temperament,
      :notes,
      :appearance,
      :image
    )
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for @pet, html: { class: "w3-container" } do |f| %>
  <% if @pet.errors.any? %>
    <div class="w3-panel w3-red w3-padding w3-margin-bottom w3-round">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-red w3-large w3-display-topright w3-round">&times;</span>
      <h3><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h3>
      <ul class="w3-ul">
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :owner_id, 'Owner', class: "w3-text-grey" %>
    <%= f.collection_select :owner_id, Owner.all.order(:fname, :lname), :id, :name, { include_blank: 'Select Owner (optional)' }, { class: "w3-select w3-border w3-round" } %>
  </p>

  <p>
    <%= f.label :name, "Name", class: "w3-text-grey" %>
    <%= f.text_field :name, class: "w3-input w3-border w3-round", required: true %>
  </p>

  <%
    is_other = !Pet::PET_TYPES.include?(@pet.pet_type) && @pet.pet_type.present?
    pet_type_selection = is_other ? "Other" : @pet.pet_type
    other_pet_type_value = is_other ? @pet.pet_type : ""
  %>

  <p>
    <%= f.label :pet_type, "Pet Type", class: "w3-text-grey" %>
    <%= f.select :pet_type, Pet::PET_TYPES + ["Other"], { include_blank: 'Select Pet Type', selected: pet_type_selection }, { class: "w3-select w3-border w3-round", id: "pet_type_select" } %>
  </p>

  <p id="other_pet_type_container" style="display: <%= is_other ? 'block' : 'none' %>;">
    <%= label_tag :pet_type_other, "Please specify", class: "w3-text-grey" %>
    <%= text_field_tag :pet_type_other, other_pet_type_value, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :breed, "Breed", class: "w3-text-grey" %>
    <%= f.text_field :breed, class: "w3-input w3-border w3-round" %>
  </p>

  <p>
    <%= f.label :gender, 'Gender', class: "w3-text-grey" %>
    <%= f.select :gender, ['Male', 'Female', 'Unknown'], { include_blank: 'Select Gender' }, { class: "w3-select w3-border w3-round" } %>
  </p>

  <p>
    <%= f.label :birthday, "Birthday", class: "w3-text-grey" %>
    <div class="custom-date-select-container">
      <%= f.date_select :birthday, { order: [:month, :day, :year], start_year: Date.current.year - 30, end_year: Date.current.year, prompt: { day: 'Day', month: 'Month', year: 'Year' } }, { class: "w3-select w3-border w3-round", style: "margin-right: 5px;" } %>
    </div>
  </p>

  <p>
    <%= f.label :temperament, "Temperament", class: "w3-text-grey" %>
    <%= f.text_area :temperament, class: "w3-input w3-border w3-round", rows: 3 %>
  </p>

  <p>
    <%= f.label :notes, "Notes", class: "w3-text-grey" %>
    <%= f.text_area :notes, class: "w3-input w3-border w3-round", rows: 4 %>
  </p>

  <p>
    <%= f.label :appearance, "Appearance", class: "w3-text-grey" %>
    <%= f.text_area :appearance, class: "w3-input w3-border w3-round", rows: 3 %>
  </p>

  <p>
    <%= f.label :image, "Image", class: "w3-text-grey" %>
    <%= f.file_field :image, class: "w3-input w3-border w3-round" %>
  </p>

  <p class="w3-center w3-padding-16">
    <%= f.submit (@pet.new_record? ? "Create Pet" : "Update Pet"), class: "w3-button w3-black w3-round-large w3-hover-dark-grey w3-padding-large" %>
  </p>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const petTypeSelect = document.getElementById('pet_type_select');
    if (!petTypeSelect) return;

    const otherPetTypeContainer = document.getElementById('other_pet_type_container');
    const otherPetTypeInput = document.querySelector('#other_pet_type_container input');

    function toggleOtherField() {
      if (petTypeSelect.value === 'Other') {
        otherPetTypeContainer.style.display = 'block';
      } else {
        otherPetTypeContainer.style.display = 'none';
        if (otherPetTypeInput) {
          otherPetTypeInput.value = '';
        }
      }
    }

    toggleOtherField();
    petTypeSelect.addEventListener('change', toggleOtherField);
  });
</script>

app/views/pets/_pet.html.erb
<% 
  image_html = nil
  if @pet.image.attached?
    image_html = image_tag(@pet.image, class: "w3-circle w3-margin-bottom", style: "width:150px; height:150px; object-fit: cover;")
  end

  attributes = [
    { label: "Pet Type", value: @pet.pet_type },
    { label: "Breed", value: @pet.breed },
    { label: "Birthday", value: @pet.birthday&.strftime("%B %d, %Y") },
    { label: "Gender", value: @pet.gender },
    { label: "Temperament", value: @pet.temperament },
    { label: "Appearance", value: @pet.appearance },
    { label: "Notes", value: @pet.notes }
  ]
%>

<%= render 'layouts/show_page',
           title: @pet.name,
           subtitle: @pet.breed,
           attributes: attributes,
           edit_path: edit_pet_path(@pet),
           resource_name: :pet,
           image_tag_html: image_html %>

app/views/pets/_pet_list_item.html.erb
<li class="w3-bar w3-padding">
  <div class="w3-bar-item">
    <span class="w3-large"><%= link_to pet.name_with_owner, pet_path(pet) %></span><br>
    <span><%= pet.breed %></span>
  </div>
</li>

app/views/pets/_pets.html.erb
<% if @owner %>
  <%= render 'owners/show', owner: @owner, show_edit_button: true %>
<% end %>

<div class="w3-container w3-section">
  <div class="w3-card w3-padding w3-round-large">
    <h3 class="w3-center">Search <%= @owner ? @owner.name + "'s" : "" %> Pets</h3>
    <div class="w3-bar w3-center w3-padding-small">
      <% search_url = request.path %>
      <%= form_with(url: search_url, local: true, method: 'get', class: "w3-container") do |f| %>
        <p>
          <%= f.label :query, 'Enter Name to Search:', class: "w3-text-grey" %>
          <%= f.text_field :query, class: "w3-input w3-border w3-round", value: params[:query] %>
        </p>
        <p class="w3-center">
          <%= f.submit 'Search', class: "w3-button w3-black w3-round w3-hover-dark-grey" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<div class="w3-container w3-section">
  <div class="w3-card-4 w3-round-large" style="overflow: hidden;">
    <header class="w3-container w3-black w3-padding w3-round-top-large">
      <div class="w3-row">
        <div class="w3-col m8 l9">
          <h2 class="w3-xlarge" style="margin-top:10px; margin-bottom:10px;">
            <%= @owner ? "Pets" : "All Pets" %>
          </h2>
        </div>
        <div class="w3-col m4 l3 w3-right-align">
          <% if @owner %>
            <%= link_to new_owner_pet_path(@owner), class: 'w3-button w3-green w3-round w3-small w3-hover-light-green w3-margin-top-small' do %>
              <i class="fa fa-plus"></i> New Pet
            <% end %>
          <% else %>
            <%= link_to new_pet_path, class: 'w3-button w3-green w3-round w3-small w3-hover-light-green w3-margin-top-small' do %>
              <i class="fa fa-plus"></i> New Pet
            <% end %>
          <% end %>
        </div>
      </div>
    </header>

    <% if @pets.present? %>
      <ul class="w3-ul w3-hoverable">
        <% @pets.each do |pet| %>
          <li class="w3-bar w3-padding">
            <div class="w3-bar-item">
              <span class="w3-large"><%= link_to pet.name_with_owner, pet_path(pet) %></span><br>
              <span><%= pet.breed %></span>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="w3-container w3-padding w3-center">
        <p><%= @owner ? "No pets found for this owner." : "No pets found." %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/_search_form.html.erb
<div class="w3-container w3-section">
  <div class="w3-card w3-padding w3-round-large">
    <h3 class="w3-center">Search <%= defined?(@owner) && @owner ? @owner.name + "'s" : "" %> Pets</h3>
    <div class="w3-bar w3-center w3-padding-small">
      <% search_url = request.path %>
      <%= form_with(url: search_url, local: true, method: 'get', class: "w3-container") do |f| %>
        <p>
          <%= f.label :query, 'Enter Name to Search:', class: "w3-text-grey" %>
          <%= f.text_field :query, class: "w3-input w3-border w3-round", value: params[:query] %>
        </p>
        <p class="w3-center">
          <%= f.submit 'Search', class: "w3-button w3-black w3-round w3-hover-dark-grey" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render layout: 'shared/w3_content_card', locals: { title: "Edit Pet: #{@pet.name}", max_width: "700px" } do %>
  <%= render 'form', pet: @pet %>
<% end %>

app/views/pets/index.html.erb
<%= render 'pets' %>

app/views/pets/new.html.erb
<%= render layout: 'shared/w3_content_card', locals: { title: (@owner ? "New Pet for #{@owner.name}" : "Create New Pet"), max_width: "700px" } do %>
  <% if flash.alert %>
    <div class="w3-panel w3-red w3-padding w3-margin-bottom w3-round">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-red w3-large w3-display-topright w3-round">&times;</span>
      <p><%= flash.alert %></p>
    </div>
  <% end %>
  <%= render 'form', pet: @pet, owner: @owner %>
<% end %>

app/views/pets/show.html.erb
<%= render 'pet' %>

<%= render 'owners/show' if @pet.owner %>