config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :walks do
    get 'all', on: :collection
    resources :pets, only: [:show]
  end

  resources :owners do
    resources :pets
  end

  resources :users
  resources :pets

  get '/auth/google_oauth2/callback', to: 'static#google_login'

  root 'static#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/walk.rb
class Walk < ApplicationRecord
  belongs_to :pet
  has_one :walker, class_name: 'User', foreign_key: 'user_id'

  scope :today, -> { where(date: DateTime.current.midnight) }
  scope :completed, -> { where(completed?: true) }

  default_scope do
    user = Thread.current[:current_user]
    if user && user.customer?
      joins(pet: :owner).where(owners: { id: user.owner&.id })
    else
      all
    end
  end

  def pickup_window
    "#{window_start.strftime('%-l:%M%P')} - #{window_end.strftime('%-l:%M%P')}"
  end

end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :authenticate_user!
  after_action :filter_walks

  def index
    @walks ||= Walk.today.order(:window_start)
  end

  def new
    @walk = Walk.new
  end

  def create
    fix_params
    @walk = Walk.create(walk_params)
    @walk.persisted? ? redirect_to(walk_path(@walk)) : render(:new)
  end

  def show
    @walk = Walk.find params[:id]
  end

  def edit
    @walk = Walk.find params[:id]
  end

  def update
    @walk = Walk.find params[:id]
    if @walk.update walk_params
      redirect_to walk_path(@walk)
    else
      flash.alert = "Update failed"
      render :edit
    end
  end

  def destroy
    walk = Walk.find params[:walk_id]
    walk.delete
  end

  def all
    @walks = Walk.all.order(:window_start)
    filter_walks
    render :index
  end

  private

  def filter_walks
    @walks = @walks.where(user_id: current_user.id) if current_user.customer?
    if @walk && @walk.user_id != current_user.id && current_user.customer?
      redirect_to root_path, alert: "You are not authorized to view this walk."
    end
  end

  def walk_params
    params.require(:walk).permit(
      :window_start,
      :window_end,
      :user_id,
      :pet_id,
      :notes,
      :walk_type,
      :completed?,
      :date
    )
  end

  def fix_params
    walk = params['walk']
    start_hour = walk['window_start(5i)'].split(':')[0]
    start_mins = walk['window_start(5i)'].split(':')[1]
    end_hour = walk['window_end(5i)'].split(':')[0]
    end_mins = walk['window_end(5i)'].split(':')[1]

    3.times.with_index do |i|
      walk["window_start(#{i+1}i)"] = walk["date(#{i+1}i)"]
      walk["window_end(#{i+1}i)"] = walk["date(#{i+1}i)"]
    end

    walk['window_start(4i)'] = start_hour
    walk['window_start(5i)'] = start_mins
    walk['window_end(4i)'] = end_hour
    walk['window_end(5i)'] = end_mins
  end
end

app/helpers/walks_helper.rb
module WalksHelper
end

app/views/walks/_form.html.erb
<%= form_for @walk, html: { class: "w3-container" } do |f| %>
  <% if @walk.errors.any? %>
    <div class="w3-panel w3-red w3-padding w3-margin-bottom w3-round">
      <span onclick="this.parentElement.style.display='none'" class="w3-button w3-red w3-large w3-display-topright w3-round">&times;</span>
      <h3><%= pluralize(@walk.errors.count, "error") %> prohibited this walk from being saved:</h3>
      <ul class="w3-ul">
        <% @walk.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :pet_id, "Pet", class: "w3-text-grey" %>
    <%= f.collection_select :pet_id, Pet.all.order(:name), :id, :name_with_owner, { include_blank: 'Select Pet' }, { class: "w3-select w3-border w3-round", required: true } %>
  </p>

  <p>
    <%= f.label :date, class: "w3-text-grey" %>
    <div class="custom-date-select-container">
      <%= f.date_select :date, { order: [:month, :day, :year], start_year: Date.current.year, end_year: Date.current.year + 1, prompt: { day: 'Day', month: 'Month', year: 'Year' } }, { class: "w3-select w3-border w3-round", style: "margin-right: 5px;", required: true } %>
    </div>
  </p>

  <div class="w3-row">
    <div class="w3-half w3-padding-right">
      <p>
        <%= f.label :window_start, 'Service Window Start', class: "w3-text-grey" %>
        <div class="custom-time-select-container">
          <%= f.time_select :window_start, { combined: true, minute_step: 30, start_hour: 8, end_hour: 20, ampm: true, ignore_date: true, time_separator: '', prompt: { hour: 'Hour', minute: 'Minute', ampm: 'AM/PM'} }, { class: "w3-select w3-border w3-round", style: "margin-right: 5px;" } %>
        </div>
      </p>
    </div>

    <div class="w3-half w3-padding-left">
      <p>
        <%= f.label :window_end, 'Service Window End', class: "w3-text-grey" %>
        <div class="custom-time-select-container">
          <%= f.time_select :window_end, { combined: true, minute_step: 30, start_hour: 9, end_hour: 21, ampm: true, ignore_date: true, time_separator: '', prompt: { hour: 'Hour', minute: 'Minute', ampm: 'AM/PM'} }, { class: "w3-select w3-border w3-round", style: "margin-right: 5px;" } %>
        </div>
      </p>
    </div>
  </div>

  <p>
    <%= f.label :walk_type, "Service Type", class: "w3-text-grey" %>
    <%= f.select :walk_type, ['15 min', '30 min', '45 min', '1 hour', 'Visit'], { selected: '30 min', include_blank: 'Select Type' }, { class: "w3-select w3-border w3-round" } %>
  </p>

  <p>
    <%= f.label :notes, "Notes for Sitter", class: "w3-text-grey" %>
    <%= f.text_area :notes, class: "w3-input w3-border w3-round", rows: 4 %>
  </p>

  <p class="w3-center w3-padding-16">
    <%= f.submit (@walk.new_record? ? "Schedule Walk" : "Update Walk"), class: "w3-button w3-black w3-round-large w3-hover-dark-grey w3-padding-large" %>
  </p>
<% end %>

app/views/walks/edit.html.erb
<h1>Edit Walk</h1>

<%= render 'form' %>

app/views/walks/index.html.erb
<div class="w3-container w3-section">
  <div class="w3-card-4 w3-round-large">
    <header class="w3-container w3-black w3-padding w3-round-top-large">
      <div class="w3-row">
        <div class="w3-col m6 l7">
          <h1 class="w3-xlarge" style="margin-top:10px; margin-bottom:10px;">
            <% if @walks.present? %>
              Walks for <%= @walks.first.date.strftime('%a, %b %e') %>
              <%= "- #{@walks.last.date.strftime('%a, %b %e')}" if @walks.first.date != @walks.last.date %>
            <% else %>
              Walks
            <% end %>
          </h1>
        </div>
        <% unless current_user.customer? %>
          <div class="w3-col m6 l5 w3-right-align w3-margin-top-small">
            <%= link_to new_walk_path, class: 'w3-button w3-green w3-round w3-small w3-hover-light-green w3-margin-right' do %>
              <i class="fa fa-plus"></i> Add New Walk
            <% end %>
            <% if !current_page?(all_walks_path) %>
              <%= link_to 'View All Walks', all_walks_path, class: 'w3-button w3-blue w3-round w3-small w3-hover-light-blue' %>
            <% else %>
              <%= link_to "View Today's Walks", walks_path, class: 'w3-button w3-blue w3-round w3-small w3-hover-light-blue' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </header>

    <%# Add Search/Filter form here if needed %>

    <% if @walks.present? %>
      <ul class="w3-ul w3-hoverable">
        <% @walks.each do |walk| %>
          <li class="w3-bar w3-padding">
            <div class="w3-bar-item">
              <span class="w3-large"><%= link_to walk.pet.name, walk_path(walk) %> (<%= walk.pet.owner.name %>)</span><br>
              <span>
                <strong>Date:</strong> <%= walk.date.strftime('%a, %b %e, %Y') %><br>
                <strong>Window:</strong> <%= walk.pickup_window %><br>
                <strong>Service:</strong> <%= walk.walk_type %>
              </span><br>
              <span>
                <strong>Address:</strong>
                <%= link_to walk.pet.owner.address, "https://www.google.com/maps/place/#{walk.pet.owner.address.gsub(' ', '+')},+#{walk.pet.owner.zip_code}", target: '_blank', class: "w3-text-blue w3-hover-text-light-blue" %>
                (<%= walk.pet.owner.zip_code %> - <%= walk.pet.owner.neighborhood %>)
              </span>
              <% if walk.notes.present? %>
                <br><span><strong>Notes:</strong> <%= walk.notes %></span>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="w3-container w3-padding w3-center">
        <p>No walks found for this period.</p>
        <%# The "Add New Walk" button is already in the header %>
      </div>
    <% end %>

    <%# Add pagination links here if needed %>
  </div>
</div>

app/views/walks/new.html.erb
<%= render layout: 'shared/w3_content_card', locals: { title: "Schedule New Walk", max_width: "700px" } do %>
  <%= render 'form', walk: @walk %>
<% end %>

app/views/walks/show.html.erb
<div class="w3-container w3-padding-16">

  <div class="w3-card-4 w3-round-large w3-margin-bottom">
    <header class="w3-container w3-center w3-black w3-padding-large w3-round-top-large">
      <h1 class="w3-xlarge">Walk Details</h1>
      <p class="w3-medium w3-text-light-grey">
        For: <%= link_to @walk.pet.name, pet_path(@walk.pet), class: "w3-text-light-grey w3-hover-text-white" %>
        on <%= @walk.date.strftime('%a, %B %e, %Y') %>
      </p>
    </header>

    <div class="w3-container w3-padding-24">

      <%# --- Walk Specifics --- %>
      <h2 class="w3-xlarge w3-border-bottom w3-padding-bottom w3-margin-bottom">Service Details</h2>
      <% walk_attributes = [
           { label: "Pickup Window", value: @walk.pickup_window },
           { label: "Service Type", value: @walk.walk_type },
           { label: "Walker Notes", value: @walk.notes } # Renamed from "Walk Notes" for clarity if walker adds them
         ] %>
      <% if @walk.completed? %>
        <% walk_attributes << { label: "Completed By", value: @walk.walker } %>
      <% end %>
      <% walk_attributes.each_with_index do |attr, index| %>
        <% if attr[:value].present? %>
          <div class="w3-row w3-padding-small profile-attribute-row">
            <div class="w3-col s12 m4 l3"><strong class="w3-text-grey"><%= attr[:label] %>:</strong></div>
            <div class="w3-col s12 m8 l9"><%= attr[:value] %></div>
          </div>
        <% end %>
      <% end %>

      <%# --- Pet Information --- %>
      <h2 class="w3-xlarge w3-border-bottom w3-padding-bottom w3-margin-top-large w3-margin-bottom">Pet Information</h2>
      <% pet_attributes = [
           { label: "Pet Name", value: link_to(@walk.pet.name, pet_path(@walk.pet)) },
           { label: "Breed", value: @walk.pet.breed },
           { label: "Gender", value: @walk.pet.gender },
           { label: "Pet Notes", value: @walk.pet.notes }, # General notes about the pet
           { label: "Temperament", value: @walk.pet.temperament }
         ] %>
      <% pet_attributes.each_with_index do |attr, index| %>
        <% if attr[:value].present? %>
          <div class="w3-row w3-padding-small profile-attribute-row">
            <div class="w3-col s12 m4 l3"><strong class="w3-text-grey"><%= attr[:label] %>:</strong></div>
            <div class="w3-col s12 m8 l9"><%= attr[:value] %></div>
          </div>
        <% end %>
      <% end %>

      <%# --- Owner & Access Information --- %>
      <h2 class="w3-xlarge w3-border-bottom w3-padding-bottom w3-margin-top-large w3-margin-bottom">Owner & Access</h2>
      <% owner_attributes = [
           { label: "Owner", value: link_to(@walk.pet.owner.name, owner_path(@walk.pet.owner)) },
           { label: "Primary Phone", value: link_to(@walk.pet.owner.phone, "tel:#{@walk.pet.owner.phone}") },
           { label: "Secondary Phone", value: (@walk.pet.owner.phone2.present? ? link_to(@walk.pet.owner.phone2, "tel:#{@walk.pet.owner.phone2}") : nil) },
           { label: "Address", value: (
             addr_str = @walk.pet.owner.address.to_s
             addr_str += " #{@walk.pet.owner.apartment_number.to_s}" if @walk.pet.owner.apartment_number.present?
             addr_str += "<br>" + @walk.pet.owner.zip_code.to_s if @walk.pet.owner.zip_code.present?
             addr_str += "<br>" + link_to('View on Google Maps', "https://www.google.com/maps/place/#{@walk.pet.owner.address.to_s.gsub(' ', '+')},+#{@walk.pet.owner.zip_code.to_s}", target: '_blank', class: 'w3-text-blue w3-hover-text-light-blue')
             addr_str.html_safe
           )},
           { label: "Lockbox Code", value: @walk.pet.owner.lockbox_code },
           { label: "Door Code", value: @walk.pet.owner.door_code },
           { label: "Entry Instructions", value: @walk.pet.owner.entry_instructions }
         ] %>
      <% owner_attributes.each_with_index do |attr, index| %>
        <% if attr[:value].present? %>
          <div class="w3-row w3-padding-small profile-attribute-row">
            <div class="w3-col s12 m4 l3"><strong class="w3-text-grey"><%= attr[:label] %>:</strong></div>
            <div class="w3-col s12 m8 l9"><%= attr[:value] %></div>
          </div>
        <% end %>
      <% end %>
    </div>

    <footer class="w3-container w3-center w3-light-grey w3-padding-16 w3-round-bottom-large">
      <%= link_to "Edit Walk", edit_walk_path(@walk), class: "w3-button w3-black w3-round-large w3-hover-dark-grey" %>
      <%# Add other actions like "Cancel Walk" or "Complete Walk" if applicable %>
    </footer>
  </div>
</div>