config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :walks do
    get 'all', on: :collection
    resources :pets, only: [:show]
  end

  resources :owners do
    resources :pets
  end

  resources :users
  resources :pets

  get '/auth/google_oauth2/callback', to: 'static#google_login'

  root 'static#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <p class="notice" style="padding: 5px; text-align: center;"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert" style="padding: 5px; text-align: center;"><%= alert %></p>
<% end %>

app/views/layouts/_index_page.html.erb
<div class="w3-container w3-section">
  <div class="w3-card-4 w3-round-large" style="overflow: hidden;">
    <header class="w3-container w3-black w3-padding w3-round-top-large">
      <div class="w3-row">
        <div class="w3-col m8 l9">
          <h1 class="w3-xlarge" style="margin-top:10px; margin-bottom:10px;"><%= title %></h1>
        </div>
        <div class="w3-col m4 l3 w3-right-align">
          <%= link_to new_path, class: 'w3-button w3-green w3-round w3-small w3-hover-light-green w3-margin-top-small' do %>
            <i class="fa fa-plus"></i> <%= new_text %>
          <% end %>
        </div>
      </div>
    </header>

    <% if local_assigns.key?(:search_form_partial) && search_form_partial.present? %>
      <%= render partial: search_form_partial %>
    <% end %>

    <% if collection.present? %>
      <ul class="w3-ul w3-hoverable">
        <% collection.each do |item| %>
          <%= render partial: item_partial, locals: { (item_partial.split('/').last.singularize.to_sym) => item } %>
        <% end %>
      </ul>
    <% else %>
      <div class="w3-container w3-padding w3-center">
        <p><%= local_assigns.key?(:no_items_message) ? no_items_message : "No items found." %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="w3-bar w3-black topnav">
  <nav>
    <% if user_signed_in? %>
      <% if current_user.customer? %>
        <%= button_to "Walks", walks_path, method: :get, class: "w3-bar-item w3-button" %>
      <% elsif current_user.employee? || current_user.admin? %>
        <%= button_to "Users", users_path, method: :get, class: "w3-bar-item w3-button" %>
        <%= button_to "Owners", owners_path, method: :get, class: "w3-bar-item w3-button" %>
        <%= button_to "Pets", pets_path, method: :get, class: "w3-bar-item w3-button" %>
        <%= button_to "Walks", walks_path, method: :get, class: "w3-bar-item w3-button" %>
      <% end %>
      <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "w3-bar-item w3-button" %>
    <% else %>
      <%= button_to "Home", root_path, method: :get, class: "w3-bar-item w3-button" %>
      <%= button_to "Log In", new_user_session_path, method: :get, class: "w3-bar-item w3-button" %>
      <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "w3-bar-item w3-button" %>
    <% end %>
  </nav>
</div>

app/views/layouts/_show_page.html.erb
<div class="w3-container w3-padding-16">
  <div class="w3-card-4 w3-round-large" style="max-width:700px; margin:auto; overflow: hidden;">

    <!-- Card Header with title & subtitle -->
    <header class="w3-container w3-center w3-black w3-padding-large w3-round-top-large">
      <% if defined?(image_tag_html) && image_tag_html.present? %>
        <%= image_tag_html.html_safe %>
      <% end %>
      <h1 class="w3-xxlarge"><%= title %></h1>
      <% if defined?(subtitle) && subtitle.present? %>
        <p class="w3-medium w3-text-light-grey"><%= subtitle %></p>
      <% end %>
    </header>

    <!-- Card Content -->
    <div class="w3-container w3-padding-16">
      <% attributes.each_with_index do |attr, index| %>
        <% if attr[:value].present? || (defined?(show_blank_values) && show_blank_values) %>
          <div class="w3-row w3-padding-small profile-attribute-row">
            <div class="w3-col m4 l3">
              <strong class="w3-text-grey"><%= attr[:label] %>:</strong>
            </div>
            <div class="w3-col m8 l9">
              <%= attr[:value] %>
            </div>
          </div>
          <% if index < attributes.select { |a| a[:value].present? || (defined?(show_blank_values) && show_blank_values) }.size - 1 %>
            <hr class="profile-hr-mobile">
          <% end %>
        <% end %>
      <% end %>
    </div>

    <% if defined?(edit_path) && edit_path.present? %>
      <footer class="w3-container w3-center w3-light-grey w3-padding-16 w3-round-bottom-large">
        <%= link_to "Edit #{resource_name.to_s.humanize.singularize}", edit_path, class: "w3-button w3-black w3-round-large w3-hover-dark-grey" %>
      </footer>
    <% end %>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oh My Dog - Rails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body class="w3-mobile">
    <%= render 'layouts/navigation' %>

    <%= render 'layouts/flash_messages' %>

    <%= yield %>

    <% if user_signed_in? %>
      <div class="w3-bar w3-center w3-light-grey">
        <span class="w3-small"><em><%= "Logged in as #{current_user.name} (#{current_user.email})" %></em></span>
      </div>
    <% end %>

  </body>

</html>